### ISSUE TITLE
Волонтерская помощь

### ISSUE THREAD

**Issue by aliesbelik** [free-belarus/initiatives#3]
Волонтерская помощь: транспорт, медикаменты, консультации, помощь в поиске людей, etc.

- [Чат автомобилистов](https://t.me/avto_help97) - развоз воды, медикаментов, людей.

**Comment by wasjawojasja** [comment]
@aliesbelik 

Перенесено в новый раздел «Инициативы». На сайте это будет [free-belarus.info/initiatives](https://free-belarus.info/initiatives/)

Подробнее о логике реорганизации в нашем телеграм-канале: [free_belarus_info](https://t.me/free_belarus_info).
